// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeserializeCredentials(arg1) {
  return window['go']['helpers']['Helper']['DeserializeCredentials'](arg1);
}

export function SaveUpdatedCredentials(arg1, arg2) {
  return window['go']['helpers']['Helper']['SaveUpdatedCredentials'](arg1, arg2);
}
