// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {helpers} from '../models';

export function DeserializeCredentials(arg1:string):Promise<helpers.WebsiteCredentials>;

export function SaveUpdatedCredentials(arg1:string,arg2:helpers.WebsiteCredentials):Promise<void>;
