// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWebsites(arg1) {
  return window['go']['main']['App']['GetWebsites'](arg1);
}

export function ReadUserSettings() {
  return window['go']['main']['App']['ReadUserSettings']();
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function UpdateUserSettings(arg1) {
  return window['go']['main']['App']['UpdateUserSettings'](arg1);
}
