// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetWebsitesWithCategories(arg1) {
  return window['go']['main']['App']['GetWebsitesWithCategories'](arg1);
}

export function GetWebsitesWithLogin() {
  return window['go']['main']['App']['GetWebsitesWithLogin']();
}

export function ReadCustomLists() {
  return window['go']['main']['App']['ReadCustomLists']();
}

export function ReadUserSettings() {
  return window['go']['main']['App']['ReadUserSettings']();
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function SelfUpdate() {
  return window['go']['main']['App']['SelfUpdate']();
}

export function UpdateCustomLists(arg1) {
  return window['go']['main']['App']['UpdateCustomLists'](arg1);
}

export function UpdateUserSettings(arg1) {
  return window['go']['main']['App']['UpdateUserSettings'](arg1);
}
